## Normalization Problem

In [23]:
import numpy as np #import the library first

X = np.random.random((5,5)) #making a 5 x 5 array of random numbers
X_Normalized = (X - X.mean()) / X.std() #normalizing the x
np.save('X_normalized.npy', X_Normalized) #saving the aaray
print (X_Normalized) #printing the result


[[-1.7680429  -0.85677489  1.35899078 -0.79373985  0.0990206 ]
 [-1.52196449 -0.39051241 -1.23676767 -1.05106715 -0.28909947]
 [-1.31519441  0.27657369 -0.87362088  1.33125406  0.48277921]
 [ 0.44730527  1.22744638  1.65364867  0.47294737  1.02063878]
 [ 1.44613008  0.37472915 -0.26756773 -0.57190076  0.74478859]]


## DIvisible By 3 Problem

In [34]:
import numpy as np #import the library

#make the ndarray
#i**2 for exponentation 
#for the first 100 integers
A = np.array([i**2 for i in range(1,101)]) 

#creating the 100 x 10 ndarray
A.reshape(10,10)

#determining the elements divisible by 3
#use modulo to find the ramainder and set to 0 to get whole number only
divisible_by_3 = A[A%3 == 0]

#saving the result as "div_by_3"
np.save('diy_by_3', divisible_by_3)

#printing the ndarray of elements that are divisible to 3
print (divisible_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
