## Normalization Problem

In [1]:
import numpy as np #import the library first

X = np.random.random((5,5)) #making a 5 x 5 array of random numbers
X_Normalized = (X - X.mean()) / X.std() #normalizing the x
np.save('X_normalized.npy', X_Normalized) #saving the aaray
print (X_Normalized) #printing the result


[[ 1.40702932 -0.36922981 -0.44669163  0.39495575  0.12844057]
 [ 0.00333907 -0.10930459 -0.34561655 -0.36480783  0.49127723]
 [-1.58491636 -0.51604836  1.59731026  0.46077559 -0.868544  ]
 [ 1.39630733 -1.34942105  0.80115197  0.95990463 -0.83563785]
 [-1.19365853 -1.42970764  1.57138962 -1.2627955   1.46449835]]


## DIvisible By 3 Problem

In [2]:
import numpy as np #import the library

#make the ndarray
#i**2 for exponentation 
#for the first 100 integers
A = np.array([i**2 for i in range(1,101)]) 

#creating the 100 x 10 ndarray
A.reshape(10,10)

#determining the elements divisible by 3
#use modulo to find the ramainder and set to 0 to get whole number only
divisible_by_3 = A[A%3 == 0]

#saving the result as "div_by_3"
np.save('diy_by_3', divisible_by_3)

#printing the ndarray of elements that are divisible to 3
print (divisible_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
